[2024-06-18T17:22:29.279+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:22:29.306+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: database_backup.backup_task manual__2024-06-18T11:37:26.129586+00:00 [queued]>
[2024-06-18T17:22:29.316+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: database_backup.backup_task manual__2024-06-18T11:37:26.129586+00:00 [queued]>
[2024-06-18T17:22:29.317+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:22:29.337+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 11:37:26.129586+00:00
[2024-06-18T17:22:29.339+0545] {standard_task_runner.py:63} INFO - Started process 7148 to run task
[2024-06-18T17:22:29.345+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'database_backup', 'backup_task', 'manual__2024-06-18T11:37:26.129586+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmp64qj2to0']
[2024-06-18T17:22:29.345+0545] {standard_task_runner.py:91} INFO - Job 28: Subtask backup_task
[2024-06-18T17:22:29.383+0545] {task_command.py:426} INFO - Running <TaskInstance: database_backup.backup_task manual__2024-06-18T11:37:26.129586+00:00 [running]> on host PRABAL-10.
[2024-06-18T17:22:29.470+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='database_backup' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:37:26.129586+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T11:37:26.129586+00:00'
[2024-06-18T17:22:29.472+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:22:29.474+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T17:22:29.475+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/prabal/bashscripts/backup.sh ']
[2024-06-18T17:22:29.483+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T17:22:29.486+0545] {subprocess.py:93} INFO - /home/prabal/bashscripts/delete.sh: line 12: syntax error near unexpected token `}'
[2024-06-18T17:22:29.486+0545] {subprocess.py:93} INFO - /home/prabal/bashscripts/delete.sh: line 12: `}'
[2024-06-18T17:22:29.494+0545] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T17:22:29.534+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T17:22:29.550+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T17:22:29.958+0545] {subprocess.py:93} INFO - /home/prabal/bashscripts/backup.sh: line 35: deleteFile: command not found
[2024-06-18T17:22:29.962+0545] {subprocess.py:93} INFO - Backup completed in 0 seconds
[2024-06-18T17:22:29.962+0545] {subprocess.py:93} INFO - Backup is Successfully done in location: /home/prabal/backup|Required Space: 0GB, Available Space: 1252.87GB
[2024-06-18T17:22:29.962+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T17:22:29.964+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:22:29.996+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=database_backup, task_id=backup_task, run_id=manual__2024-06-18T11:37:26.129586+00:00, execution_date=20240618T113726, start_date=20240618T113729, end_date=20240618T113729
[2024-06-18T17:22:30.040+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T17:22:30.077+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:22:30.084+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
