[2024-06-18T13:48:54.572+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:48:54.597+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:48:54.603+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:48:54.603+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:48:54.621+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 07:50:00+00:00
[2024-06-18T13:48:54.624+0545] {standard_task_runner.py:63} INFO - Started process 16100 to run task
[2024-06-18T13:48:54.626+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-18T07:50:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmpe3r7m5c_']
[2024-06-18T13:48:54.627+0545] {standard_task_runner.py:91} INFO - Job 4: Subtask send_mail
[2024-06-18T13:48:54.667+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T13:48:54.738+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:50:00+00:00'
[2024-06-18T13:48:54.739+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:48:54.749+0545] {logging_mixin.py:188} WARNING - /home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T13:48:54.749+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T13:49:25.067+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:49:25.068+0545] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
[2024-06-18T13:49:25.088+0545] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-18T07:50:00+00:00, execution_date=20240618T075000, start_date=20240618T080354, end_date=20240618T080425
[2024-06-18T13:49:25.118+0545] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task send_mail ([Errno 101] Network is unreachable; 16100)
[2024-06-18T13:49:25.135+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T13:49:25.145+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:49:25.146+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T13:51:39.106+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:51:39.148+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:51:39.161+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:51:39.162+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:51:39.188+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 07:50:00+00:00
[2024-06-18T13:51:39.192+0545] {standard_task_runner.py:63} INFO - Started process 16905 to run task
[2024-06-18T13:51:39.199+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-18T07:50:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmp8yk2gasm']
[2024-06-18T13:51:39.201+0545] {standard_task_runner.py:91} INFO - Job 4: Subtask send_mail
[2024-06-18T13:51:39.260+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T13:51:39.333+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:50:00+00:00'
[2024-06-18T13:51:39.335+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:51:39.355+0545] {logging_mixin.py:188} WARNING - /home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T13:51:39.356+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T13:51:42.108+0545] {email.py:282} INFO - Sent an alert email to ['avyuthan364@gmail.com']
[2024-06-18T13:51:44.464+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:51:44.472+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-18T07:50:00+00:00, execution_date=20240618T075000, start_date=20240618T080639, end_date=20240618T080644
[2024-06-18T13:51:44.509+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T13:51:44.529+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:51:44.530+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T13:52:58.600+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T13:52:58.632+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:52:58.641+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [queued]>
[2024-06-18T13:52:58.642+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T13:52:58.662+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 07:50:00+00:00
[2024-06-18T13:52:58.665+0545] {standard_task_runner.py:63} INFO - Started process 17338 to run task
[2024-06-18T13:52:58.670+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-18T07:50:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/backup.py', '--cfg-path', '/tmp/tmpnx64ms7m']
[2024-06-18T13:52:58.671+0545] {standard_task_runner.py:91} INFO - Job 4: Subtask send_mail
[2024-06-18T13:52:58.721+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T07:50:00+00:00 [running]> on host PRABAL-10.
[2024-06-18T13:52:58.833+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prabal' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T07:50:00+00:00'
[2024-06-18T13:52:58.834+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T13:52:58.847+0545] {logging_mixin.py:188} WARNING - /home/prabal/afenv/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T13:52:58.847+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T13:53:00.862+0545] {email.py:282} INFO - Sent an alert email to ['prabalkuinkel10@gmail.com']
[2024-06-18T13:53:02.903+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T13:53:02.912+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-18T07:50:00+00:00, execution_date=20240618T075000, start_date=20240618T080758, end_date=20240618T080802
[2024-06-18T13:53:02.955+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T13:53:02.974+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T13:53:02.975+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
